#!/bin/bash
cd /data/sfsf/workspace/trunk/tomcat-sfs/bin
tomcat_pid=`ps aux | grep tomcat | grep -v grep`
if [ -n "${tomcat_pid}" ]
then
    ps aux | grep tomcat | grep -v grep | awk '{print $2}' | xargs kill -9 && sleep 2 && ./startSFS.sh jrebel=off
else
	./startSFS.sh jrebel=off
fi

sleep 1
> ../logs/server.log
tail -f ../logs/server.log

